# -*- coding: utf-8 -*-
# 
# WARNING: Do not edit this file unless you know what you are doing.
# See https://github.com/zhangjinbao520/BaWangCan
# 
# __author__ = "ZhangJinbao"
# Copyright(C) 2021 ZhangJinbao All rights reserved.
#
# 作用：
#    1、霸王餐（免费试）的报名线程

import requests, time, re, json, os

class runResultThread():
    '''
    免费试执行的自定义线程
    作用：自动报名免费试，生成表格、并微信推送报名结果
    '''
    def __init__(self, Cookie, userNickName=None, City=None, CityId=None, SCKEY=None):
        super().__init__()
        self.Cookie = Cookie
        self.userNickName = userNickName
        self.City = City
        self.CityId = CityId
        self.SCKEY = SCKEY

    def run(self):
        '''
        run()重写
        '''
        self.PASS = 0
        self.SKIP = 0
        self.FAIL = 0
        self.MESSAGE = ''
        count = 1
        activityTitles = self.getBaWangCanList()    # 获取霸王餐列表
        for _activity in activityTitles:
            # 霸王餐报名
            self.MESSAGE += '{0}、{1}\n'.format(count, _activity['activityTitle'])
            offlineActivityId = _activity['detailUrl'].replace('http://s.dianping.com/event/', '')
            self.MESSAGE += ' - 【报名结果】：{}\n\n'.format(self.runBaWangCan(offlineActivityId))
            count += 1
        self.MESSAGE = '---\n\n-----开始报名霸王餐（免费试）-----\n\n用户名：***{0}***\n\n城 市：***{1}***\n\n- 今日报名成功：**{2}**\n\n- 今日报名重复：**{3}**\n\n- 今日报名异常：**{4}**\n\n---\n\n-----今日成果预览-----\n\n'.format(self.userNickName, self.City, self.PASS, self.SKIP, self.FAIL) + self.MESSAGE
        self.weixinTrap()    # 微信推送

    def getBaWangCanList(self):
        '''
        获取霸王餐列表
        '''
        detail = []
        url = 'http://m.dianping.com/activity/static/pc/ajaxList'
        headers = {
            'Content-Type': 'application/json',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36'
        }
        data = {
            'cityId': self.CityId,
            'mode': "",
            'page': 1,
            'type': 0,    # type：霸王餐类型
        }
        while True:
            response = requests.post(url=url, headers=headers, data=json.dumps(data))
            if response.status_code == 200:
                hasNext = response.json()['data']['hasNext']
                detail += response.json()['data']['detail']
                if hasNext:    # 是否还有下一页列表
                    data['page'] += 1
                else:
                    break
            else:
                break
        return detail
    
    def runBaWangCan(self, activatyID):
        '''
        报名霸王餐
        '''
        url = 'http://s.dianping.com/ajax/json/activity/offline/saveApplyInfo'
        headers = {
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8;',
            'Cookie': self.Cookie,
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36',
        }
        data = {
            'offlineActivityId': activatyID,
            'phoneNo': '',
            'shippingAddress': '',
            'extraCount': '',
            'birthdayStr': '',
            'email': '',
            'marryDayStr': time.strftime('%Y-%m-%d'),
            'babyBirths': time.strftime('%Y-%m-%d'),
            'pregnant': '',
            'marryStatus': '0',
            'comboId': '',
            'branchId': '',
            'usePassCard': '0',
            'passCardNo': '',
            'isShareSina': 'true',
            'isShareQQ': 'true',
        }
        response = requests.post(url=url, headers=headers, data=data)
        if response.status_code == 200:
            msg = response.json()['msg']['html']
            if '报名成功' in msg:
                msg = '报名成功'
                self.PASS += 1
            elif '已经报过名了，不要重复报名' in msg:
                self.SKIP += 1
            else:
                self.FAIL += 1
        else:
            msg = '报名异常'
            self.FAIL += 1
        return msg

    def weixinTrap(self):
        '''
        微信推送
        '''
        # 从http://sc.ftqq.com/?c=code获取微信推送的SCKEY，并绑定官微
        # SCKEY = 'SCU155771T3549c0427011a83c02d53a4f054055166012211d21350'    # Server酱申请的SCKEY
        url = 'https://sc.ftqq.com/{}.send'.format(self.SCKEY)
        header = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36',}
        data = {
            'text': '大众点评免费试运行结果',
            'desp': self.MESSAGE,
        }
        requests.post(url=url, headers=header, data=data)

if __name__ == '__main__':
    COOKIE = os.environ['COOKIE']
    NICKNAME = os.environ['NICKNAME']
    CITY = os.environ['CITY']
    CITYID = os.environ['CITYID']
    SCKEY = os.environ['SCKEY']
    BaWangCan = runResultThread(COOKIE, NICKNAME, CITY, CITYID, SCKEY)
    BaWangCan.run()
