# -*- coding: utf-8 -*-
#
# WARNING: Do not edit this file unless you know what you are doing.
# See https://github.com/zhangjinbao520/BaWangCan
#
# __author__ = "ZhangJinbao"
# Copyright(C) 2021 ZhangJinbao All rights reserved.
#
# 作用：
#    1、读写“config.ini”配置文件

from configparser import RawConfigParser  # 用于读写config.ini


class Config(object):
    def __init__(self, file="config.ini"):
        super().__init__()
        self.file = file
        self.config = RawConfigParser()
        self.config.read(self.file, encoding="utf-8")  # 读取文件

    def getConfig(self, section, option):
        """
        读取config.ini配置文件
        """
        try:
            return self.config.get(section, option)
        except:
            return None

    def saveConfig(self, section, option, value=None):
        """
        保存config.ini配置文件
        """
        try:
            self.config.add_section(section)  # 如果键值不存在，则创建键值
        except:
            pass
        self.config.set(section, option, value)
        self.config.write(
            open(self.file, "w+", encoding="utf-8"))  # 写入文件（读写模式）
