# -*- coding: utf-8 -*-
#
# WARNING: Do not edit this file unless you know what you are doing.
# See https://github.com/zhangjinbao520/BaWangCan
#
# __author__ = 'ZhangJinbao'
#
# 作用：自动生成【area.py】文件

import json

import requests

dictProvince = {}
dictCity = {}


def getAllProvince():
    """
    获取省份列表
    """
    url = "https://www.dianping.com/ajax/citylist/getAllDomesticProvince"
    header = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
    }
    response = requests.post(url=url, headers=header)
    if response.status_code == 200:
        provinces = response.json()["provinceList"]
        for _province in provinces:
            provinceName = _province["provinceName"]
            provinceId = _province["provinceId"]
            dictProvince[provinceName] = provinceId
            dictCity[provinceName] = getAllCity(provinceId)


def getAllCity(provinceId):
    """
    获取省份所对应的城市列表
    """
    cityList = {}
    url = "https://www.dianping.com/ajax/citylist/getDomesticCityByProvince"
    header = {
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
    }
    data = {
        "provinceId": provinceId,
    }
    response = requests.post(url=url, headers=header, data=json.dumps(data))
    if response.status_code == 200:
        citys = response.json()["cityList"]
        for _city in citys:
            cityList[_city["cityName"]] = _city["cityId"]
    return cityList


if __name__ == "__main__":
    getAllProvince()
    openfile = open("area.py", "a+", encoding="utf-8")  # 打开文件
    openfile.write("dictProvince = {0}\n".format(str(dictProvince)))
    openfile.write("dictCity = {\n")
    for key, value in dictCity.items():
        openfile.write("    '{0}':{1},\n".format(key, str(value)))
    openfile.write("}")
    openfile.close()
